/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangunDatar;

/**
 *
 * @author DELL
 */
public class MainBangunRuang extends javax.swing.JFrame {

    /**
     * Creates new form MainBangunRuang
     */
    public MainBangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tbSisiPersegi = new javax.swing.JTextField();
        btnHLPersegi = new javax.swing.JButton();
        btnHKPersegi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbHLPsg = new javax.swing.JLabel();
        lbHKPsg = new javax.swing.JLabel();
        btnClearPersegi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tbPPerPan = new javax.swing.JTextField();
        btnHLPerPan = new javax.swing.JButton();
        btnHKPerPan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbHKPerPan = new javax.swing.JLabel();
        btnClearPerPan = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tbLPerPan = new javax.swing.JTextField();
        lbHLPerPan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tbAlasS3 = new javax.swing.JTextField();
        btnHLS3 = new javax.swing.JButton();
        btnHKS3 = new javax.swing.JButton();
        btnClearS3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbHLS3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbHKS3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tbTinggiS3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnHLLingkaran = new javax.swing.JButton();
        tbJejari = new javax.swing.JTextField();
        btnHKLingkaran = new javax.swing.JButton();
        btnClearLingkaran = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbHLLingkaran = new javax.swing.JLabel();
        lbHKLingkaran = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel15.setText("jLabel15");

        setTitle("Hitung Bangun Datar");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("Bangun Datar");

        jLabel2.setText("Sisi");

        tbSisiPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSisiPersegiActionPerformed(evt);
            }
        });

        btnHLPersegi.setText("Hitung Luas");
        btnHLPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHLPersegiActionPerformed(evt);
            }
        });

        btnHKPersegi.setText("Hitung Keliling");
        btnHKPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHKPersegiActionPerformed(evt);
            }
        });

        jLabel3.setText("Luas Persegi :");

        jLabel4.setText("Keliling Persegi : ");

        lbHLPsg.setText("0");

        lbHKPsg.setText("0");

        btnClearPersegi.setText("Clear");
        btnClearPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersegiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tbSisiPersegi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHLPersegi)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHKPsg)
                            .addComponent(lbHLPsg)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHKPersegi)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearPersegi)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbSisiPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHLPersegi)
                    .addComponent(btnHKPersegi)
                    .addComponent(btnClearPersegi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbHLPsg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbHKPsg))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persegi", jPanel1);

        jLabel5.setText("Panjang");

        tbPPerPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPPerPanActionPerformed(evt);
            }
        });

        btnHLPerPan.setText("Hitung Luas");
        btnHLPerPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHLPerPanActionPerformed(evt);
            }
        });

        btnHKPerPan.setText("Hitung Keliling");
        btnHKPerPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHKPerPanActionPerformed(evt);
            }
        });

        jLabel8.setText("Luas Persegi Panjang :");

        jLabel9.setText("Keliling Persegi Panjang : ");

        lbHKPerPan.setText("0");

        btnClearPerPan.setText("Clear");
        btnClearPerPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPerPanActionPerformed(evt);
            }
        });

        jLabel24.setText("Lebar");

        tbLPerPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLPerPanActionPerformed(evt);
            }
        });

        lbHLPerPan.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHLPerPan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHKPerPan)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearPerPan))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                            .addComponent(tbLPerPan, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tbPPerPan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHLPerPan)
                            .addComponent(lbHKPerPan))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbPPerPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tbLPerPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHLPerPan)
                    .addComponent(btnHKPerPan)
                    .addComponent(btnClearPerPan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbHLPerPan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbHKPerPan))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persegi Panjang", jPanel2);

        jLabel12.setText("Alas");

        tbAlasS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAlasS3ActionPerformed(evt);
            }
        });

        btnHLS3.setText("Hitung Luas");
        btnHLS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHLS3ActionPerformed(evt);
            }
        });

        btnHKS3.setText("Hitung Keliling");
        btnHKS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHKS3ActionPerformed(evt);
            }
        });

        btnClearS3.setText("Clear");
        btnClearS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearS3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Luas Segitiga : ");

        lbHLS3.setText("0");

        jLabel18.setText("Keliling Segitiga : ");

        lbHKS3.setText("0");

        jLabel25.setText("Tinggi");

        tbTinggiS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTinggiS3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbTinggiS3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(tbAlasS3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHLS3)
                        .addGap(18, 18, 18)
                        .addComponent(btnHKS3)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearS3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHLS3)
                            .addComponent(lbHKS3))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbAlasS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTinggiS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHLS3)
                    .addComponent(btnHKS3)
                    .addComponent(btnClearS3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbHLS3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbHKS3))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Segitiga", jPanel3);

        jLabel13.setText("Jejari");

        btnHLLingkaran.setText("Hitung Luas");
        btnHLLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHLLingkaranActionPerformed(evt);
            }
        });

        tbJejari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbJejariActionPerformed(evt);
            }
        });

        btnHKLingkaran.setText("Hitung Keliling");
        btnHKLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHKLingkaranActionPerformed(evt);
            }
        });

        btnClearLingkaran.setText("Clear");
        btnClearLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLingkaranActionPerformed(evt);
            }
        });

        jLabel20.setText("Luas Lingkaran : ");

        jLabel21.setText("Keliling Lingkaran : ");

        lbHLLingkaran.setText("0");

        lbHKLingkaran.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tbJejari))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnHLLingkaran)
                                .addGap(18, 18, 18)
                                .addComponent(btnHKLingkaran)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearLingkaran)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbHLLingkaran))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(12, 12, 12)
                                .addComponent(lbHKLingkaran)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbJejari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHLLingkaran)
                    .addComponent(btnHKLingkaran)
                    .addComponent(btnClearLingkaran))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbHLLingkaran))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lbHKLingkaran))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lingkaran", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHLPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHLPersegiActionPerformed
        // TODO add your handling code here:
        // mengambil data dr textbox
        String sisi = tbSisiPersegi.getText();
        
        // mengubah str mjd doub
        double doubleSisi = Double.valueOf(sisi);
        
        Persegi persegi = new Persegi(doubleSisi);
        
        double hasilLuas = persegi.hitungLuas();
        String strHL = String.valueOf(hasilLuas);
        
        lbHLPsg.setText(strHL + " cm^2");
    }//GEN-LAST:event_btnHLPersegiActionPerformed

    private void btnHKPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHKPersegiActionPerformed
        // TODO add your handling code here:
        String sisi = tbSisiPersegi.getText();
        
        double doubleSisi = Double.valueOf(sisi);
        
        Persegi persegi = new Persegi(doubleSisi);
        double hasilKeliling = persegi.hitungKeliling();
        String strHK = String.valueOf(hasilKeliling);
        
        lbHKPsg.setText(strHK + " cm");
    }//GEN-LAST:event_btnHKPersegiActionPerformed

    private void btnClearPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPersegiActionPerformed
        // TODO add your handling code here:
        // masukkan semua textbox utk clear
        tbSisiPersegi.setText("");
        lbHLPsg.setText("0");
        lbHKPsg.setText("0");
    }//GEN-LAST:event_btnClearPersegiActionPerformed

    private void tbAlasS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAlasS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAlasS3ActionPerformed

    private void btnHKS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHKS3ActionPerformed
        // TODO add your handling code here:
        String Alas = tbAlasS3.getText();
        String Tinggi = tbTinggiS3.getText();
        
        double doubleAlas = Double.valueOf(Alas);
        double doubleTinggi = Double.valueOf(Tinggi);
        
        SegiTiga segitiga = new SegiTiga (doubleAlas, doubleTinggi);
        
        double hasilKeliling = segitiga.hitungKeliling();
        String strHK = String.valueOf(hasilKeliling);
        
        lbHKS3.setText(strHK + " cm");
    }//GEN-LAST:event_btnHKS3ActionPerformed

    private void btnHKPerPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHKPerPanActionPerformed
        // TODO add your handling code here:
        String Panjang = tbPPerPan.getText();
        String Lebar = tbLPerPan.getText();

        double doublePanjang = Double.valueOf(Panjang);
        double doubleLebar = Double.valueOf(Lebar);
        
        PersegiPanjang perpan = new PersegiPanjang (doublePanjang, doubleLebar);
        
        double hasilKeliling = perpan.hitungKeliling();
        String strHK = String.valueOf(hasilKeliling);
        
        lbHKPerPan.setText(strHK + " cm");

    }//GEN-LAST:event_btnHKPerPanActionPerformed

    private void tbPPerPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPPerPanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPPerPanActionPerformed

    private void btnHKLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHKLingkaranActionPerformed
        // TODO add your handling code here:
        String Jejari = tbJejari.getText();
        double doubleJejari = Double.valueOf(Jejari);
        
        Lingkaran lingkaran = new Lingkaran(doubleJejari);
        double hasilKeliling = lingkaran.hitungKeliling();
        String strHK = String.valueOf(hasilKeliling);
        
        lbHKLingkaran.setText(strHK + " cm");
    }//GEN-LAST:event_btnHKLingkaranActionPerformed

    private void tbLPerPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLPerPanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLPerPanActionPerformed

    private void tbSisiPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSisiPersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSisiPersegiActionPerformed

    private void tbTinggiS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTinggiS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTinggiS3ActionPerformed

    private void btnHLPerPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHLPerPanActionPerformed
        // TODO add your handling code here:
        String Panjang = tbPPerPan.getText();
        String Lebar = tbLPerPan.getText();
        
        double doublePanjang = Double.valueOf(Panjang);
        double doubleLebar = Double.valueOf(Lebar);
        
        PersegiPanjang perpan = new PersegiPanjang (doublePanjang, doubleLebar);
        
        double hasilLuas = perpan.hitungLuas();
        String strHL = String.valueOf(hasilLuas);
        
        lbHLPerPan.setText(strHL + " cm^2");
    }//GEN-LAST:event_btnHLPerPanActionPerformed

    private void btnClearPerPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPerPanActionPerformed
        // TODO add your handling code here:
        tbPPerPan.setText("");
        tbLPerPan.setText("");
        lbHLPerPan.setText("0");
        lbHKPerPan.setText("0");
    }//GEN-LAST:event_btnClearPerPanActionPerformed

    private void btnClearS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearS3ActionPerformed
        // TODO add your handling code here:
        tbAlasS3.setText("");
        tbTinggiS3.setText("" );
        lbHLS3.setText("0");
        lbHKS3.setText("0");
    }//GEN-LAST:event_btnClearS3ActionPerformed

    private void btnHLS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHLS3ActionPerformed
        // TODO add your handling code here:
        String Alas = tbAlasS3.getText();
        String Tinggi = tbTinggiS3.getText();

        double doubleAlas = Double.valueOf(Alas);
        double doubleTinggi = Double.valueOf(Tinggi);
        
        SegiTiga segitiga= new SegiTiga (doubleAlas, doubleTinggi);
        
        double hasilLuas = segitiga.hitungLuas();
        String strHL = String.valueOf(hasilLuas);
        
       lbHLS3.setText(strHL + " cm^2");
    }//GEN-LAST:event_btnHLS3ActionPerformed

    private void btnHLLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHLLingkaranActionPerformed
        // TODO add your handling code here:
        String Jejari = tbJejari.getText();
        double doubleJejari = Double.valueOf(Jejari);
        
        Lingkaran lingkaran = new Lingkaran (doubleJejari);
        
        double hasilLuas = lingkaran.hitungLuas();
        String strHL = String.valueOf(hasilLuas);
        
        lbHLLingkaran.setText(strHL + " cm^2");

        
    }//GEN-LAST:event_btnHLLingkaranActionPerformed

    private void tbJejariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbJejariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbJejariActionPerformed

    private void btnClearLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLingkaranActionPerformed
        // TODO add your handling code here:
        tbJejari.setText("");
        lbHLLingkaran.setText("0");
        lbHKLingkaran.setText("0");
    }//GEN-LAST:event_btnClearLingkaranActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLingkaran;
    private javax.swing.JButton btnClearPerPan;
    private javax.swing.JButton btnClearPersegi;
    private javax.swing.JButton btnClearS3;
    private javax.swing.JButton btnHKLingkaran;
    private javax.swing.JButton btnHKPerPan;
    private javax.swing.JButton btnHKPersegi;
    private javax.swing.JButton btnHKS3;
    private javax.swing.JButton btnHLLingkaran;
    private javax.swing.JButton btnHLPerPan;
    private javax.swing.JButton btnHLPersegi;
    private javax.swing.JButton btnHLS3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbHKLingkaran;
    private javax.swing.JLabel lbHKPerPan;
    private javax.swing.JLabel lbHKPsg;
    private javax.swing.JLabel lbHKS3;
    private javax.swing.JLabel lbHLLingkaran;
    private javax.swing.JLabel lbHLPerPan;
    private javax.swing.JLabel lbHLPsg;
    private javax.swing.JLabel lbHLS3;
    private javax.swing.JTextField tbAlasS3;
    private javax.swing.JTextField tbJejari;
    private javax.swing.JTextField tbLPerPan;
    private javax.swing.JTextField tbPPerPan;
    private javax.swing.JTextField tbSisiPersegi;
    private javax.swing.JTextField tbTinggiS3;
    // End of variables declaration//GEN-END:variables
}
